CREATE TABLE InventoryStore (
    id INT AUTO_INCREMENT PRIMARY KEY,
    inventoryId VARCHAR(255) NOT NULL,
    storeId VARCHAR(255) NOT NULL,
    managerId VARCHAR(255),
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);